### ISSUE TITLE
Show lootspec

### ISSUE THREAD

**Issue by cremor** [NumyAddon/TalentLoadoutBroker#1]
Could you please also show the current loot spec in the LDB display (either with an additional icon or with text)?
Maybe also add an option for it so that people who don't want to see it can disable it.

**Comment by Numynum** [comment]
I've added the ability to fully customize the text, including showing the lootspec icon/text :)
edit: it's in the latest release, which should show up on curse in a few minutes)

**Comment by cremor** [comment]
Thanks, but it seems like there is an issue with `%lootspecIcon%`. It only shows a number for me, not an icon.
`%lootspecIcon2%` works fine.

**Comment by Numynum** [comment]
seems I rushed it a bit yesterday 🙂 fixed in next update 👌
