### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by Andf** [NumyAddon/TalentLoadoutBroker#5]
Hi there!

Getting the following errors after today update:

1x ...eTalentLoadoutBroker/TalentLoadoutBroker.lua:461: attempt to index local 'talentsTab' (a nil value)
[string "@TalentLoadoutBroker/TalentLoadoutBroker.lua"]:461: in function `UpdateLastSelectedSavedConfigID'
[string "@TalentLoadoutBroker/TalentLoadoutBroker.lua"]:480: in function <...eTalentLoadoutBroker/TalentLoadoutBroker.lua:475>

Locals:
self = <table> {
 defaults = <table> {
 }
 displaySpecName = "Enhancement"
 RefreshMenuListLoadouts = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:186
 SelectSpec = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:424
 SortTLMLoadouts = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:266
 RefreshMenuListSpecs = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:339
 ToggleLoadoutDropDown = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:108
 SetTextLoadout = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:118
 SetTextIsSwitching = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:130
 ACTIVE_PLAYER_SPECIALIZATION_CHANGED = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:546
 OnTooltipShow = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:84
 GetTalentFrame = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:441
 updatePending = false
 OnButtonClick = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:92
 SelectLoadout = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:399
 SetTextSpec = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:122
 menuList = <table> {
 }
 displayIsSwitching = true
 currentConfigID = 43464054
 displaySpecIcon = 237581
 pendingConfigID = 43464068
 TRAIT_CONFIG_UPDATED = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:469
 ToggleSpecDropDown = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:113
 displayLootSpecIcon = 237581
 displayLootSpecName = "Enhancement"
 displayLoadoutName = "Sin WH"
 db = <table> {
 }
 configIDToName = <table> {
 }
 eventFrame = Frame {
 }
 GetTalentFrameContainer = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:446
 SPELLS_CHANGED = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:528
 SPECIALIZATION_CHANGE_CAST_FAILED = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:552
 ignoreHook = false
 Init = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:11
 configIDs = <table> {
 }
 TalentLoadoutLDB = <table> {
 }
 SetTextLootSpec = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:126
 PLAYER_LOOT_SPEC_UPDATED = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:557
 SetText = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:134
 menuListDefaults = <table> {
 }
 SelectLootSpec = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:432
 dropDown = Frame {
 }
 FormatSpecText = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:182
 UpdateLastSelectedSavedConfigID = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:453
 pendingDisableStarterBuild = false
 CONFIG_COMMIT_FAILED = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:500
}
configID = 43464068
talentsTab = nil
(*temporary) = <table> {
 defaults = <table> {
 }
 displaySpecName = "Enhancement"
 RefreshMenuListLoadouts = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:186
 SelectSpec = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:424
 SortTLMLoadouts = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:266
 RefreshMenuListSpecs = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:339
 ToggleLoadoutDropDown = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker.lua:108
 SetTextLoadout = <function> defined @TalentLoadoutBroker/TalentLoadoutBroker

**Comment by Numynum** [comment]
thanks, fixed 🙂

**Comment by Andf** [comment]
Jolly good (and swift) job, thanks! Just got 1.2.19, works like a charm!
